apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name | quote }}
  labels:
  {{- include "node_cert_exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "node_cert_exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
      {{- include "node_cert_exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name | quote }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - "--v=2"
            - "--logtostderr=true"
            - "--path={{- range $path_counter, $path_value := $.Values.paths }}{{ if ne $path_counter 0 }},{{ end }}{{ $path_value }}{{- end }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 9117
              name: http
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /host/etc
              name: etc
              readOnly: true
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - hostPath:
            path: /etc
            type: ""
          name: etc
  updateStrategy:
    type: RollingUpdate