---
apiVersion: v1
kind: Namespace
metadata:
  name: node-cert-exporter
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-cert-exporter
  namespace: node-cert-exporter
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: node-cert-exporter
  name: node-cert-exporter
  namespace: node-cert-exporter
spec:
  selector:
    matchLabels:
      app: node-cert-exporter
  template:
    metadata:
      name: node-cert-exporter
      labels:
        app: node-cert-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9117'
    spec:
      containers:
      - image: amimof/node-cert-exporter:latest
        args:
        - "--v=2"
        - "--logtostderr=true"
        - "--path=/host/etc/origin/node/,/host/etc/origin/master/,/host/etc/etcd/,/host/etc/kubernetes/pki/"
        name: node-cert-exporter
        ports:
        - containerPort: 9117
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /host/etc
          name: etc
          readOnly: true
      serviceAccount: node-cert-exporter
      serviceAccountName: node-cert-exporter
      volumes:
      - hostPath:
          path: /etc
          type: ""
        name: etc
  updateStrategy:
    type: RollingUpdate